# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Mafia.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bMafia.proto\"\x1a\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x06\x41nswer\x12\x14\n\x0c\x65mptyMessage\x18\x01 \x01(\t\"\x17\n\x04Info\x12\x0f\n\x07message\x18\x01 \x01(\t2o\n\x04Game\x12\x1f\n\x08JoinGame\x12\x08.Request\x1a\x07.Answer\"\x00\x12 \n\tLeaveGame\x12\x08.Request\x1a\x07.Answer\"\x00\x12$\n\rUpdatePlayers\x12\x08.Request\x1a\x05.Info\"\x00\x30\x01\x62\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_ANSWER = DESCRIPTOR.message_types_by_name['Answer']
_INFO = DESCRIPTOR.message_types_by_name['Info']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'Mafia_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

Answer = _reflection.GeneratedProtocolMessageType('Answer', (_message.Message,), {
  'DESCRIPTOR' : _ANSWER,
  '__module__' : 'Mafia_pb2'
  # @@protoc_insertion_point(class_scope:Answer)
  })
_sym_db.RegisterMessage(Answer)

Info = _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), {
  'DESCRIPTOR' : _INFO,
  '__module__' : 'Mafia_pb2'
  # @@protoc_insertion_point(class_scope:Info)
  })
_sym_db.RegisterMessage(Info)

_GAME = DESCRIPTOR.services_by_name['Game']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=15
  _REQUEST._serialized_end=41
  _ANSWER._serialized_start=43
  _ANSWER._serialized_end=73
  _INFO._serialized_start=75
  _INFO._serialized_end=98
  _GAME._serialized_start=100
  _GAME._serialized_end=211
# @@protoc_insertion_point(module_scope)
